# Generated by Django 3.2 on 2021-05-28 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id_columna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id_tablero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=99)),
                ('descripcion', models.CharField(max_length=99)),
                ('detalle', models.CharField(max_length=255)),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=99)),
                ('apellidop', models.CharField(max_length=99)),
                ('apellidom', models.CharField(max_length=99)),
                ('cargo', models.CharField(max_length=50)),
                ('id_rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea_tipo',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('descripcion', models.CharField(max_length=99)),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea_columna',
            fields=[
                ('id_tarea_columna', models.IntegerField(primary_key=True, serialize=False)),
                ('id_columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.columna')),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tarea_tipo'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='rol',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.IntegerField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=255)),
                ('comentario', models.CharField(max_length=255)),
                ('reporte', models.BooleanField()),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='columna',
            name='id_tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablero'),
        ),
    ]
