# Generated by Django 3.2 on 2021-07-10 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id_columna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('posicion', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('final', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id_flujo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=99)),
                ('apellidop', models.CharField(max_length=99, null=True)),
                ('apellidom', models.CharField(max_length=99, null=True)),
                ('cargo', models.CharField(max_length=50, null=True)),
                ('ultimo_tablero', models.IntegerField(null=True)),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea_tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('descripcion', models.CharField(blank=True, max_length=99, null=True)),
                ('id_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('descripcion', models.CharField(max_length=99)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('estado_avance', models.IntegerField(blank=True, null=True)),
                ('posicion', models.IntegerField()),
                ('id_columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.columna')),
                ('id_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.documento')),
                ('id_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarea_tipo')),
                ('tarea_madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarea')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id_tablero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flujo_detalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('posicion_tarea', models.IntegerField()),
                ('id_columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.columna')),
                ('id_flujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flujo')),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=255)),
                ('comentario', models.CharField(max_length=255)),
                ('reporte', models.BooleanField()),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='columna',
            name='id_tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablero'),
        ),
    ]
