# Generated by Django 3.2 on 2021-06-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidom',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidop',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
