# Generated by Django 3.2 on 2021-06-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultimo_tablero',
            field=models.IntegerField(null=True),
        ),
    ]
