# Generated by Django 3.2 on 2021-06-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_ultimo_tablero'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
